version: "3.7"
services:
  app:
    build:
      args:
        user: uloydev
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: dicky
    container_name: dicky-app
    restart: unless-stopped
    working_dir: /var/www/
    depends_on:
      - mariadb
    volumes:
      - ./:/var/www
    networks:
      - dicky
  nginx:
    image: nginx:1.17-alpine
    container_name: dicky-nginx
    restart: unless-stopped
    ports:
      - 8061:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - dicky
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dicky
      MYSQL_USER: dicky
      MYSQL_PASSWORD: dicky
    networks:
      - dicky
    restart: on-failure
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - databaseVolume:/var/lib/mysql
volumes:
  databaseVolume:
networks:
  dicky:
    driver: bridge
